name: CI

on:
  pull_request:
    branches:
      - main

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install -r app/requirements.txt

      - name: Run Tests
        run: |
          pytest app/tests \
            --junitxml=report.xml \
            --cov=app

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: report.xml

      - name: Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .